### ISSUE TITLE
Runtime Binary (extension)

### ISSUE THREAD

**Issue by rahulc8y** [SoftwareAG/iot-cumulocity-events-graph#1]
If the effort for converting it is low, please consider converting it to a plugin and providing a runtime binary. 

![grafik](https://github.com/SoftwareAG/iot-cumulocity-events-graph/assets/116082992/70de981b-fbc8-43c3-baeb-218ca8eef41c)

**Comment by hnaether-c8y** [comment]
Thanks for the finding. I updated the zip file in the release. This is indeed a plugin. Runtime binaries for Application builder are out of scope for me.
